export type OrganizerErrorCode =
  | "INVALID_FILE_ID"
  | "FILE_NOT_FOUND"
  | "FILE_CHANGED"
  | "UNSAFE_PATH"
  | "INSPECTION_FAILED"
  | "CLASSIFICATION_INVALID_SUBMISSION"
  | "PLAN_INVALID_CLASSIFICATION"
  | "PLAN_UNSAFE_FILENAME"
  | "PLAN_UNSAFE_DESTINATION"
  | "PLAN_DESTINATION_TOO_LONG"
  | "PLAN_VALIDATION_FAILED"
  | "INVALID_PLAN_ID"
  | "PLAN_EXPIRED"
  | "PLAN_ALREADY_USED"
  | "PLAN_CHANGED"
  | "PLAN_CONFLICT"
  | "INVALID_DIRECTORY_PLAN_ID"
  | "DIRECTORY_PLAN_EXPIRED"
  | "DIRECTORY_PLAN_ALREADY_USED"
  | "DIRECTORY_PLAN_CHANGED"
  | "DIRECTORY_PLAN_CONFLICT"
  | "INVALID_DIRECTORY_CONFIRMATION_ID"
  | "DIRECTORY_CONFIRMATION_EXPIRED"
  | "DIRECTORY_CONFIRMATION_ALREADY_EXECUTING"
  | "DIRECTORY_CONFIRMATION_INVALIDATED"
  | "DIRECTORY_EXECUTION_CHANGED"
  | "DIRECTORY_EXECUTION_CONFLICT"
  | "DIRECTORY_EXECUTION_PARTIAL"
  | "DIRECTORY_EXECUTION_FAILED"
  | "INVALID_CONFIRMATION_ID"
  | "CONFIRMATION_EXPIRED"
  | "CONFIRMATION_ALREADY_EXECUTING"
  | "CONFIRMATION_ALREADY_USED"
  | "CONFIRMATION_INVALIDATED"
  | "EXECUTION_CHANGED"
  | "EXECUTION_CONFLICT"
  | "EXECUTION_DESTINATION_UNAVAILABLE"
  | "EXECUTION_CROSS_FILESYSTEM"
  | "EXECUTION_PARTIAL"
  | "EXECUTION_STORAGE_FAILED"
  | "EXECUTION_FAILED";

export class OrganizerError extends Error {
  override readonly name = "OrganizerError";

  constructor(
    readonly code: OrganizerErrorCode,
    message: string,
    options?: ErrorOptions,
  ) {
    super(message, options);
  }
}
